version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
   configuration: sdk/python/docs/source/conf.py

formats:
   - pdf

python:
  version: "3.10"
  install:
      - requirements: sdk/python/docs/requirements.txt
