name: linter

on: [push, pull_request]

jobs:
  lint-python:
    runs-on: [ubuntu-latest]
    env:
      PYTHON: 3.11
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: |
          make install-python-ci-dependencies-uv
          make compile-protos-go
      - name: Lint python
        run: make lint-python
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5
      - name: Lint go
        run: make lint-go
  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          submodules: recursive
      - name: Lint java
        run: make lint-java
